project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Remotely Sensing Cities and Environments LearnDiary"
  author: "Yanxi Ren"
  date: "1/20/2026"
  sidebar:
    style: docked
    search: true
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4&5.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bib
number-sections: false

format:
  html:
    theme: 
      - cosmo
    toc: true
    toc-location: right

editor: visual

